---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/cf-bg
    tag: "1.0"

run:
  path: pipeline-repo/ci/scripts/deploy.sh

- put: app-data
  params:
    file: 'app_data*.txt'
    acl: public-read

inputs:
- name: release
  path: release_tar

