---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/cf-bg
    tag: "1.0"

run:
  path: pipeline-repo/ci/scripts/deploy.sh

inputs:
- name: release
  path: release_tar
- name: pipeline-repo
  path: pipeline-repo

