---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: allomov/cf-cli
    tag: v1.3

run:
  path: pipeline-repo/ci/scripts/run-sched-test.sh

inputs:
- name: pipeline-repo
