---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: agf234/pcfdev-cli
    tag: "2.0"

run:
  path: pipeline-repo/ci/scripts/run-doc-gen.sh

inputs:
- name: pipeline-repo
- name: test-data

outputs:
- name: outputs
  path: outputs

